### ISSUE TITLE
0.4.2: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by asolino** [etingof/pyasn1#110]
Hey @etingof:

While testing 0.4.1/0.4.2 against [impacket](https://github.com/CoreSecurity/impacket) I noticed an error is thrown when using the [GetADUsers.py](https://github.com/CoreSecurity/impacket/blob/master/examples/GetADUsers.py) script. It was correctly working with `pyasn1-0.3.7`. This is the error thrown, any idea?:

```
Impacket v0.9.16-dev - Copyright 2002-2017 Core Security Technologies

Password:
[*] Querying freefly.net for information about domain. Be patient...
Traceback (most recent call last):
  File "./GetADUsers.py", line 265, in <module>
    executer.run()
  File "./GetADUsers.py", line 150, in run
    sizeLimit=0, searchControls = [sc])
  File "/Users/beto/src/impacket/impacket/ldap/ldap.py", line 369, in search
    response = self.sendReceive(searchRequest, searchControls)
  File "/Users/beto/src/impacket/impacket/ldap/ldap.py", line 458, in sendReceive
    self.send(request, controls)
  File "/Users/beto/src/impacket/impacket/ldap/ldap.py", line 418, in send
    data = encoder.encode(message)
  File "build/bdist.macosx-10.13-intel/egg/pyasn1/codec/ber/encoder.py", line 663, in __call__
    substrate = concreteEncoder.encode(value, asn1Spec, self, **options)
  File "build/bdist.macosx-10.13-intel/egg/pyasn1/codec/ber/encoder.py", line 85, in encode
    value, asn1Spec, encodeFun, **options
  File "build/bdist.macosx-10.13-intel/egg/pyasn1/codec/ber/encoder.py", line 450, in encodeValue
    chunk = encodeFun(component, asn1Spec, **options)
  File "build/bdist.macosx-10.13-intel/egg/pyasn1/codec/ber/encoder.py", line 663, in __call__
    substrate = concreteEncoder.encode(value, asn1Spec, self, **options)
  File "build/bdist.macosx-10.13-intel/egg/pyasn1/codec/ber/encoder.py", line 85, in encode
    value, asn1Spec, encodeFun, **options
  File "build/bdist.macosx-10.13-intel/egg/pyasn1/codec/ber/encoder.py", line 502, in encodeValue
    substrate += encodeFun(value[idx], asn1Spec, **options)
  File "build/bdist.macosx-10.13-intel/egg/pyasn1/codec/ber/encoder.py", line 663, in __call__
    substrate = concreteEncoder.encode(value, asn1Spec, self, **options)
  File "build/bdist.macosx-10.13-intel/egg/pyasn1/codec/ber/encoder.py", line 85, in encode
    value, asn1Spec, encodeFun, **options
  File "build/bdist.macosx-10.13-intel/egg/pyasn1/codec/ber/encoder.py", line 437, in encodeValue
    for idx, component in enumerate(value.values()):
  File "build/bdist.macosx-10.13-intel/egg/pyasn1/type/univ.py", line 2096, in values
    yield self[idx]
  File "build/bdist.macosx-10.13-intel/egg/pyasn1/type/univ.py", line 2060, in __getitem__
    return self.getComponentByPosition(idx)
  File "build/bdist.macosx-10.13-intel/egg/pyasn1/type/univ.py", line 2290, in getComponentByPosition
    self.setComponentByPosition(idx)
  File "/Users/beto/src/impacket/impacket/ldap/ldapasn1.py", line 553, in setComponentByPosition
    matchConstraints=matchConstraints)
  File "build/bdist.macosx-10.13-intel/egg/pyasn1/type/univ.py", line 2359, in setComponentByPosition
    value = subComponentType.clone(value=value)
  File "build/bdist.macosx-10.13-intel/egg/pyasn1/type/base.py", line 349, in clone
    return self.__class__(value, **initilaizers)
  File "build/bdist.macosx-10.13-intel/egg/pyasn1/type/univ.py", line 103, in __init__
    base.AbstractSimpleAsn1Item.__init__(self, value, **kwargs)
  File "build/bdist.macosx-10.13-intel/egg/pyasn1/type/base.py", line 240, in __init__
    value = self.prettyIn(value)
  File "build/bdist.macosx-10.13-intel/egg/pyasn1/type/univ.py", line 254, in prettyIn
    return int(value)
TypeError: int() argument must be a string or a number, not 'NoneType'
None
int() argument must be a string or a number, not 'NoneType'
``` 
Thanks!

**Comment by etingof** [comment]
The root cause of this is that since  pyasn1 0.4.x the `None` initializer for a [no-value condition](https://github.com/CoreSecurity/impacket/blob/c001138f76075e602f16f7ac143bcb409f1dfef2/impacket/ldap/ldapasn1.py#L538) is gone. Suggested way is to use the `noValue` object instead of `None`. The `noValue` sentinel should work for pyasn1 0.1.8+.

This is a potentially breaking change indeed. We can get `None` back to preserve compatibility with existing applications at the expense of somewhat cluttered code inside pyasn1.

The question is - how hard it would be for the Impacket project to replace `None` with `noValue`?

**Comment by asolino** [comment]
Hey @etingof 

Thanks for your quick answer. That indeed solved the issue on my side. 
Replacing `None` with `noValues` where appropriate won't be a big deal, so there's no need to preserve compatibility in this case. 

thanks again!
