### ISSUE TITLE
Doesn't support GeneralizedTime format on V0.3.* and V0.4.*?

### ISSUE THREAD

**Issue by KingjZhang** [etingof/pyasn1#114]
I am using python3.5 and pyasn1 library for parse the X509 certficate. I found a issue is the pyasn1 V0.3.* and V0.4.* doesn't support GeneralizedTime format. I can read the valid date when roll back to V0.2.3.

**Comment by etingof** [comment]
Thank you for reporting this!

Could I have a simple reproducer to understand the issue?

**Comment by KingjZhang** [comment]
Thank you for quick response. I am using the Atmel AWS IoT Zero Touch python script to parse a certficate. The certificate notBefore is DATEFMT_RFC5280_UTC format. If I set notAfter to over 3000 years in certficate, the notAfter will be DATEFMT_RFC5280_GEN format. I got an error stack as follwing when I using this script:

https://github.com/MicrochipTech/aws-iot-zero-touch-secure-provisioning-kit/blob/802e506bdec57bb21d6c055f7c7818104cbae018/cert2certdef.py#L269

python3 cert2certdef.py --device-cert device.crt 

Traceback (most recent call last):
  File "cert2certdef.py", line 658, in <module>
    main()
  File "cert2certdef.py", line 44, in main
    print(gen_cert_def_c_device(cert_der))
  File "cert2certdef.py", line 129, in gen_cert_def_c_device
    not_after  = set_time_params(params, cert, 'notAfter')
  File "cert2certdef.py", line 199, in set_time_params
    info = cert_time_offset_length(cert, name)
  File "cert2certdef.py", line 269, in cert_time_offset_length
    time_str = str(cert_mod['tbsCertificate']['validity'][name][idx])
  File "/usr/local/lib/python3.5/dist-packages/pyasn1/type/char.py", line 88, in __str__
    return str(self._value)
  File "/usr/local/lib/python3.5/dist-packages/pyasn1/type/base.py", line 164, in plug
    raise error.PyAsn1Error('Uninitialized ASN.1 value ("%s" attribute looked up)' % name)
pyasn1.error.PyAsn1Error: Uninitialized ASN.1 value ("__str__" attribute looked up)

**Comment by etingof** [comment]
Which pyasn1 version you are using?

My guess is that the actual problem is [here](https://github.com/MicrochipTech/aws-iot-zero-touch-secure-provisioning-kit/blob/802e506bdec57bb21d6c055f7c7818104cbae018/cert2certdef.py#L267). When you check for field value presence, starting from pyasn1 0.2.3, you should use the `.hasValue()` method instead (or along with) the `None` comparison:

    if not cert_mod['tbsCertificate']['validity'][name][idx].hasValue():

BTW, even then the code seems shaky because once you increment `idx` you do not run any value presence check on the `idx+1` field.
