### ISSUE TITLE
ValueConstraintError and issue with choice types

### ISSUE THREAD

**Issue by Bujko** [etingof/pyasn1#124]
Hi!

I have converted an ASN.1 file by asn1ate to python code.
I have got a problem that i can't solve.
(I am storing the classes in Schema.py)

linkage_value ='030303030303030303'

class LinkageValue(univ.OctetString):
    pass

LinkageValue.subtypeSpec = constraint.ValueSizeConstraint(9, 9)

lv = Schema.LinkageValue()
lv = linkage_value

print(lv)

This code above is working.

But the code below not, and I don't understand why.
I have tryed many different ways but I didn't succeed.

class LinkageData(univ.Sequence):
    pass

LinkageData.componentType = namedtype.NamedTypes(
    namedtype.NamedType('iCert', IValue().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('linkage-value', LinkageValue().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('group-linkage-value', GroupLinkageValue().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 2)))
)

ld = Schema.LinkageData()
print('ok1')
ld.setComponentByName('iCert', icert)
print('ok2')
ld['linkage-value'] = lv

The output of this code is(not the whole) :

ok1
ok2
Traceback (most recent call last):
  File "/home/kraudy97/.local/lib/python3.6/site-packages/pyasn1/type/constraint.py", line 32, in __call__
    self._testValue(value, idx)
  File "/home/kraudy97/.local/lib/python3.6/site-packages/pyasn1/type/constraint.py", line 297, in _testValue
    raise error.ValueConstraintError(value)
pyasn1.type.error.ValueConstraintError: b'030303030303030303'

Seems to be the same problem here:

class EccP256CurvePoint(univ.Choice):
    pass

EccP256CurvePoint.componentType = namedtype.NamedTypes(
    namedtype.NamedType('x-only', univ.OctetString().subtype(subtypeSpec=constraint.ValueSizeConstraint(32, 32)).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('fill', univ.Null().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.NamedType('compressed-y-0', univ.OctetString().subtype(subtypeSpec=constraint.ValueSizeConstraint(32, 32)).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.NamedType('compressed-y-1', univ.OctetString().subtype(subtypeSpec=constraint.ValueSizeConstraint(32, 32)).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.NamedType('uncompressed', univ.Sequence(componentType=namedtype.NamedTypes(
        namedtype.NamedType('x', univ.OctetString().subtype(subtypeSpec=constraint.ValueSizeConstraint(32, 32)).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
        namedtype.NamedType('y', univ.OctetString().subtype(subtypeSpec=constraint.ValueSizeConstraint(32, 32)).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1)))
    ))
    .subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 4)))
)

class VerificationKeyIndicator(univ.Choice):
    pass

VerificationKeyIndicator.componentType = namedtype.NamedTypes(
    namedtype.NamedType('verificationKey', PublicVerificationKey().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 0))),
    namedtype.NamedType('reconstructionValue', EccP256CurvePoint().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 1)))
)

eccp256_value = '0808080808080808080808080808080808080808080808080808080808080808'

vk_try = Schema.VerificationKeyIndicator()
vk_try['reconstructionValue'].setComponentByName('compressed-y-1', eccp256_value)

eccp256_try = Schema.EccP256CurvePoint()
eccp256_try.setComponentByName('compressed-y-1', eccp256_value)

eccp256 = Schema.EccP256CurvePoint()
eccp256['compressed-y-1'] = eccp256_value # '0808080808080808080808080808080808080808080808080808080808080808'

The output of the code (full, but cut of the full path, it's not relevant):

Traceback (most recent call last):
  File "...pyasn1/type/constraint.py", line 32, in __call__
    self._testValue(value, idx)
  File "...pyasn1/type/constraint.py", line 297, in _testValue
    raise error.ValueConstraintError(value)
pyasn1.type.error.ValueConstraintError: b'0808080808080808080808080808080808080808080808080808080808080808'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...pyasn1/type/constraint.py", line 32, in __call__
    self._testValue(value, idx)
  File "...pyasn1/type/constraint.py", line 497, in _testValue
    constraint(value, idx)
  File "...pyasn1/type/constraint.py", line 36, in __call__
    '%s failed at: %r' % (self, sys.exc_info()[1])
pyasn1.type.error.ValueConstraintError: <ValueSizeConstraint object at 0x7fdcde6d9b38 consts 32, 32> failed at: ValueConstraintError(b'0808080808080808080808080808080808080808080808080808080808080808',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...pyasn1/type/base.py", line 242, in __init__
    self.subtypeSpec(value)
  File "...pyasn1/type/constraint.py", line 36, in __call__
    '%s failed at: %r' % (self, sys.exc_info()[1])
pyasn1.type.error.ValueConstraintError: <ConstraintsIntersection object at 0x7fdcde6d9b70 consts <ValueSizeConstraint object at 0x7fdcde6d9b38 consts 32, 32>> failed at: ValueConstraintError("<ValueSizeConstraint object at 0x7fdcde6d9b38 consts 32, 32> failed at: ValueConstraintError(b'0808080808080808080808080808080808080808080808080808080808080808',)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testcert.py", line 79, in <module>
    vk_try['reconstructionValue'].setComponentByName('compressed-y-1', eccp256_value)
  File "...pyasn1/type/univ.py", line 2207, in setComponentByName
    idx, value, verifyConstraints, matchTags, matchConstraints
  File "...pyasn1/type/univ.py", line 2865, in setComponentByPosition
    Set.setComponentByPosition(self, idx, value, verifyConstraints, matchTags, matchConstraints)
  File "...pyasn1/type/univ.py", line 2359, in setComponentByPosition
    value = subComponentType.clone(value=value)
  File "...pyasn1/type/base.py", line 349, in clone
    return self.__class__(value, **initilaizers)
  File "...pyasn1/type/univ.py", line 819, in __init__
    base.AbstractSimpleAsn1Item.__init__(self, value, **kwargs)
  File "...pyasn1/type/base.py", line 246, in __init__
    raise exType('%s at %s' % (exValue, self.__class__.__name__))
pyasn1.type.error.ValueConstraintError: <ConstraintsIntersection object at 0x7fdcde6d9b70 consts <ValueSizeConstraint object at 0x7fdcde6d9b38 consts 32, 32>> failed at: ValueConstraintError("<ValueSizeConstraint object at 0x7fdcde6d9b38 consts 32, 32> failed at: ValueConstraintError(b'0808080808080808080808080808080808080808080808080808080808080808',)",) at OctetString

I have tryed to give you all of my information.

What am I doing wrong? How can I solve this?

**Comment by Bujko** [comment]
The problem solved by converting the strings by bytes.fromhex()
