### ISSUE TITLE
AttributeError: 'property' object has no attribute 'presentTypes'

### ISSUE THREAD

**Issue by davidsielert** [etingof/pyasn1#127]
I'm not sure about this I don't know much of python myself, coming from another script (freeipa) (ipa-server-install)

```File "/usr/lib/python2.7/site-packages/ipalib/x509.py", line 45, in <module>
    from pyasn1_modules import rfc2315, rfc2459
  File "/usr/lib/python2.7/site-packages/pyasn1_modules/rfc2315.py", line 67, in <module>
    class DigestedData(univ.Sequence):
  File "/usr/lib/python2.7/site-packages/pyasn1_modules/rfc2315.py", line 72, in DigestedData
    namedtype.NamedType('digest', Digest)
  File "/root/.local/lib/python2.7/site-packages/pyasn1/type/namedtype.py", line 159, in __init__
    self.__ambiguousTypes = 'terminal' not in kwargs and self.__computeAmbiguousTypes() or {}
  File "/root/.local/lib/python2.7/site-packages/pyasn1/type/namedtype.py", line 278, in __computeAmbiguousTypes
    ambigiousTypes[idx] = NamedTypes(*partialAmbigiousTypes, **dict(terminal=True))
  File "/root/.local/lib/python2.7/site-packages/pyasn1/type/namedtype.py", line 158, in __init__
    self.__tagToPosMap = self.__computeTagToPosMap()
  File "/root/.local/lib/python2.7/site-packages/pyasn1/type/namedtype.py", line 251, in __computeTagToPosMap
    for _tagSet in tagMap.presentTypes:
AttributeError: 'property' object has no attribute 'presentTypes'```

**Comment by etingof** [comment]
This import:

    from pyasn1_modules import rfc2315, rfc2459

does not produce this error with my setup (the latest released pyasn1/pyasn1-modules).

Could you please share your `pip freeze` output? I suspect some inconsistency in pyasn1/pyasn1-modules versions you have installed.

**Comment by modassarrana** [comment]
I am also facing the same issue . 
pip freeze output 
```
paramiko==2.1.1
pbr==5.2.0
perf==0.1
ply==3.4
policycoreutils-default-encoding==0.1
prettytable==0.7.2
pyasn1==0.4.5
pyasn1-modules==0.0.8
pycparser==2.14
pycrypto==2.6.1
pycryptodomex==3.8.1
pycurl==7.19.0
pygobject==3.22.0
pygpgme==0.3
pyliblzma==0.5.3
pyserial==2.6
pysmi==0.3.4
```
rpm package for python2-pyasn1 is 
```
rpm -qa | grep python2-pyasn1
python2-pyasn1-modules-0.1.9-7.el7.noarch
python2-pyasn1-0.1.9-7.el7.noarch
```
Please let me know , how to resolve it asap

**Comment by etingof** [comment]
> pyasn1-modules==0.0.8

This version ^ is very old

> python2-pyasn1-modules-0.1.9-7.el7.noarch

As well as this. ^

Also, it looks like you have a mix of pyasn1 packages installed.

Please update to the latest released pyasn1/pyasn1-modules and make sure you are importing the right ones:

```
$ python -c 'import pyasn1; print(pyasn1.__version__)'
0.4.7
```

**Comment by modassarrana** [comment]
I have upgrade pyasn1-modules to latest & rerun to verify import package version. Before it was 0.4.5 & now its 0.4.7
[root@svpod7mgmt002 ping]# python -c 'import pyasn1; print(pyasn1.__version__)'
0.4.7

```
pip freeze
pyasn1==0.4.7
pyasn1-modules==0.2.6
```

That issue is resolved , but now i am getting below 

```

[root@svpod7mgmt002 ping]# ipa-server-install --setup-dns
Traceback (most recent call last):
  File "/sbin/ipa-server-install", line 23, in <module>
    from ipaserver.install import ipa_server_install
  File "/usr/lib/python2.7/site-packages/ipaserver/install/ipa_server_install.py", line 10, in <module>
    from ipaserver.install.server import ServerMasterInstall
  File "/usr/lib/python2.7/site-packages/ipaserver/install/server/__init__.py", line 31, in <module>
    from .install import validate_admin_password, validate_dm_password
  File "/usr/lib/python2.7/site-packages/ipaserver/install/server/install.py", line 33, in <module>
    from ipaserver.install import (
  File "/usr/lib/python2.7/site-packages/ipaserver/install/ca.py", line 23, in <module>
    from ipaserver.install import cainstance, bindinstance, dsinstance
  File "/usr/lib/python2.7/site-packages/ipaserver/install/cainstance.py", line 72, in <module>
    from ipaserver.install.dogtaginstance import DogtagInstance
  File "/usr/lib/python2.7/site-packages/ipaserver/install/dogtaginstance.py", line 32, in <module>
    from pki.client import PKIConnection
  File "/usr/lib/python2.7/site-packages/pki/__init__.py", line 35, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 32, in <module>
    from .exceptions import InvalidURL
  File "/usr/lib/python2.7/site-packages/requests/exceptions.py", line 10, in <module>
    from .packages.urllib3.exceptions import HTTPError as BaseHTTPError
  File "/usr/lib/python2.7/site-packages/requests/packages/__init__.py", line 95, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'requests.packages.urllib3'
```

**Comment by modassarrana** [comment]
Forgot to mention that urllib3 is already installed by pip
```
[root@svpod7mgmt002 ping]# pip install urllib3
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: urllib3 in /usr/lib/python2.7/site-packages (1.24.3)
```

**Comment by etingof** [comment]
I think this is unrelated to pyasn1. Try this though:

```
pip install requests urllib3 --force --upgrade
```

**Comment by modassarrana** [comment]
I tried that option. That didn't work . So i tried below option & that has worked now.
pip uninstall requests
pip uninstall urllib3
yum remove python-urllib3
yum remove python-requests
yum install python-urllib3
yum install python-requests

**Comment by modassarrana** [comment]
Can i setup ipa server as docker container. If yes , do you have any document related to it

**Comment by etingof** [comment]
> Can i setup ipa server as docker container. If yes , do you have any document related to it

As far as pyasn1 is concerned - most certainly. But I have no clue as for the IPA thing per se.
