### ISSUE TITLE
sysDescr.0 response raise error.ValueConstraintError(value)

### ISSUE THREAD

**Issue by JohnHay** [etingof/pyasn1#141]
I'm using python 3.6 and did a pip-3.6 install of pysnmp 4.4.5, which installed pyasn1 0.4.4. I started with multiple-concurrent-queries1.py, removed all targets, adding only this one. I also removed sysLocation from the request.

I found that all of our switches with a specific firmware version, would cause pyasn1 some pain when doing pysnmp getCmd of sysDescr.0. The rest do not give an error and print the expected output.

#######
Traceback (most recent call last):
  File "/home/jhay/.local/lib/python3.6/site-packages/pyasn1/type/constraint.py", line 32, in __call__
    self._testValue(value, idx)
  File "/home/jhay/.local/lib/python3.6/site-packages/pyasn1/type/constraint.py", line 297, in _testValue
    raise error.ValueConstraintError(value)
pyasn1.type.error.ValueConstraintError: b'TiMOS-B-7.0.R8 both/hops ALCATEL SAS-T 12F10T 4XFP 7210 Copyright (c) 2000-2015 Alcatel-Lucent.\r\nAll rights reserved. All use subject to applicable license agreements.\r\nBuilt on Thu Jul 30 13:48:21 IST 2015 by builder in /home/builder/7.0B1/R8/panos/main\r\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jhay/.local/lib/python3.6/site-packages/pyasn1/type/constraint.py", line 32, in __call__
    self._testValue(value, idx)
  File "/home/jhay/.local/lib/python3.6/site-packages/pyasn1/type/constraint.py", line 497, in _testValue
    constraint(value, idx)
  File "/home/jhay/.local/lib/python3.6/site-packages/pyasn1/type/constraint.py", line 36, in __call__
    '%s failed at: %r' % (self, sys.exc_info()[1])
pyasn1.type.error.ValueConstraintError: <ValueSizeConstraint object at 0x80922fc18 consts 0, 255> failed at: ValueConstraintError(b'TiMOS-B-7.0.R8 both/hops ALCATEL SAS-T 12F10T 4XFP 7210 Copyright (c) 2000-2015 Alcatel-Lucent.\r\nAll rights reserved. All use subject to applicable license agreements.\r\nBuilt on Thu Jul 30 13:48:21 IST 2015 by builder in /home/builder/7.0B1/R8/panos/main\r\n',)

During handling of the above exception, another exception occurred:
#######

The complete error output is attached:
[pysnmp-error.txt](https://github.com/etingof/pyasn1/files/2283993/pysnmp-error.txt)

John

**Comment by Jasonjiang27** [comment]
have this issue resolved?
