### ISSUE TITLE
Can't decode native encoded AttributeTypeAndValue with univ.Choice inside

### ISSUE THREAD

**Issue by geckyan** [etingof/pyasn1#160]
I was using pyasn1 0.4.5 and rfc5280 module to:

* decode the public key certificate,
* encode it to native Python objects,
* make some changes,
* and revert it all the way back to the der binary format.

But I've encountered an error "TypeError: 'str' object cannot be interpreted as an integer" when tried to decode from native Python representation of AttributeTypeAndValue with X520StateOrProvinceName value lying inside.

Minimal working example:

```py
from pyasn1.codec.native import decoder, encoder
from pyasn1.type import univ, char
from pyasn1.type.namedtype import NamedType, NamedTypes
from pyasn1.type.opentype import OpenType
import pyasn1.debug as debug

debug.setLogger(debug.Debug('all'))

class FooChoice(univ.Choice):
    componentType = NamedTypes(NamedType('utf8String', char.UTF8String()))

fooTypeMap = { univ.ObjectIdentifier('1.2.3'): FooChoice() }

class FooType(univ.ObjectIdentifier): pass
class FooValue(univ.Any): pass

class FooTypeAndValue(univ.Sequence):
    componentType = NamedTypes(
        NamedType('type', FooType()),
        NamedType('value', FooValue(), openType=OpenType('type', fooTypeMap))
    )

fooTV = FooTypeAndValue()
fooTV['type'] = univ.ObjectIdentifier('1.2.3')
fooChoice = FooChoice()
fooChoice['utf8String'] = 'bar'
fooTV.setComponentByName('value', fooChoice)

natified = encoder.encode(fooTV)
print(f'Natified object: {natified}')
print(decoder.decode(natified, FooTypeAndValue()))
```

Debug log:

```log
2019-06-08 19:03:57,175 pyasn1: running pyasn1 0.4.5, debug flags all2019-06-08 19:03:57,175 pyasn1: debug category 'all' enabled
2019-06-08 19:03:57,176 pyasn1: encoder called for type FooTypeAndValue <FooTypeAndValue:
 type=1.2.3 value=FooChoice:
  utf8String=bar

>
2019-06-08 19:03:57,176 pyasn1: using value codec SequenceEncoder chosen by <TagSet object at 0x3bd2dd0 tags 0:32:16>
2019-06-08 19:03:57,176 pyasn1: encoder called for type ObjectIdentifier <1.2.3>
2019-06-08 19:03:57,176 pyasn1: using value codec ObjectIdentifierEncoder chosen by <TagSet object at 0x3bd28b0 tags 0:0:6>
2019-06-08 19:03:57,177 pyasn1: encoder ObjectIdentifierEncoder produced: '1.2.3'
2019-06-08 19:03:57,177 pyasn1: encoder called for type FooChoice <FooChoice:
 utf8String=bar
>
2019-06-08 19:03:57,177 pyasn1: using value codec ChoiceEncoder chosen by <TagSet object at 0x3be3090 untagged>
2019-06-08 19:03:57,178 pyasn1: encoder called for type UTF8String <bar>
2019-06-08 19:03:57,178 pyasn1: using value codec OctetStringEncoder chosen by <TagSet object at 0x3be3270 tags 0:0:12>
2019-06-08 19:03:57,179 pyasn1: encoder OctetStringEncoder produced: b'bar'
2019-06-08 19:03:57,179 pyasn1: encoder ChoiceEncoder produced: OrderedDict([('utf8String', b'bar')])
2019-06-08 19:03:57,179 pyasn1: encoder SequenceEncoder produced: OrderedDict([('type', '1.2.3'), ('value', OrderedDict([('utf8String', b'bar')]))])
Natified object: OrderedDict([('type', '1.2.3'), ('value', OrderedDict([('utf8String', b'bar')]))])
2019-06-08 19:03:57,179 pyasn1: decoder called at scope OrderedDict, working with type OrderedDict
2019-06-08 19:03:57,180 pyasn1: calling decoder SequenceOrSetDecoder on Python type OrderedDict <OrderedDict([('type', '1.2.3'), ('value', OrderedDict([('utf8String', b'bar')]))])>
2019-06-08 19:03:57,180 pyasn1: decoder called at scope OrderedDict.str, working with type str
2019-06-08 19:03:57,180 pyasn1: calling decoder AbstractScalarDecoder on Python type str <'1.2.3'>
2019-06-08 19:03:57,181 pyasn1: decoder AbstractScalarDecoder produced ASN.1 type FooType <<FooType value object at 0x3be3990 tagSet <TagSet object at 0x3bd28b0 tags 0:0:6> payload [1.2.3]>>
2019-06-08 19:03:57,181 pyasn1: decoder called at scope OrderedDict.OrderedDict, working with type OrderedDict
2019-06-08 19:03:57,181 pyasn1: calling decoder AbstractScalarDecoder on Python type OrderedDict <OrderedDict([('utf8String', b'bar')])>
Traceback (most recent call last):
  File "native_opentype.py", line 31, in <module>
    print(decoder.decode(natified, FooTypeAndValue()))
  File "C:\Users\k.german\.virtualenvs\parts_generator-vSBLwntT\lib\site-packages\pyasn1\codec\native\decoder.py", line 164, in __call__
    value = valueDecoder(pyObject, asn1Spec, self, **options)
  File "C:\Users\k.german\.virtualenvs\parts_generator-vSBLwntT\lib\site-packages\pyasn1\codec\native\decoder.py", line 38, in __call__
    asn1Value[field] = decodeFun(pyObject[field], componentsTypes[field].asn1Object, **options)
  File "C:\Users\k.german\.virtualenvs\parts_generator-vSBLwntT\lib\site-packages\pyasn1\codec\native\decoder.py", line 164, in __call__
    value = valueDecoder(pyObject, asn1Spec, self, **options)
  File "C:\Users\k.german\.virtualenvs\parts_generator-vSBLwntT\lib\site-packages\pyasn1\codec\native\decoder.py", line 22, in __call__
    return asn1Spec.clone(pyObject)
  File "C:\Users\k.german\.virtualenvs\parts_generator-vSBLwntT\lib\site-packages\pyasn1\type\base.py", line 349, in clone
    return self.__class__(value, **initializers)
  File "C:\Users\k.german\.virtualenvs\parts_generator-vSBLwntT\lib\site-packages\pyasn1\type\univ.py", line 819, in __init__
    base.AbstractSimpleAsn1Item.__init__(self, value, **kwargs)
  File "C:\Users\k.german\.virtualenvs\parts_generator-vSBLwntT\lib\site-packages\pyasn1\type\base.py", line 240, in __init__
    value = self.prettyIn(value)
  File "C:\Users\k.german\.virtualenvs\parts_generator-vSBLwntT\lib\site-packages\pyasn1\type\univ.py", line 878, in prettyIn
    return bytes(value)
TypeError: 'str' object cannot be interpreted as an integer
```

**Comment by etingof** [comment]
Thank you for reporting this issue!

It appears, that `openType` feature is not implemented for the native decoder. Let me see if we could add it there.
