### ISSUE TITLE
How to manually downgrade an ASN.1 spec to X.208?

### ISSUE THREAD

**Issue by holviberker** [etingof/pyasn1#169]
I'm trying to decode data by using the ASN.1 specification described at https://www.etsi.org/deliver/etsi_ts/119400_119499/119495/01.03.02_60/ts_119495v010302p.pdf. Since pyasn1 doesn't support X.60X yet, I have to manually generate pyasn1 code manually. I've tried to apply the suggestions at https://tools.ietf.org/html/draft-ietf-pkix-asn1-translation-01#section-4.1 but I couldn't be able to generate it automatically.

```asn
ETSIPSD2QcprofileMod { itu-t(0) identified-organization(4) etsi(0) psd2(19495) idmod(0) id-modpsd2qcprofile(0) }

DEFINITIONS EXPLICIT TAGS ::=

BEGIN

-- EXPORTS All –-

IMPORTS
QC-STATEMENT
 FROM PKIXqualified97 {iso(1) identified-organization(3) dod(6)
 internet(1) security(5) mechanisms(5) pkix(7) id-mod(0)
 id-mod-qualified-cert-97(35)};

-- statements

etsi-psd2-qcStatement QC-STATEMENT ::= { SYNTAX PSD2QcType IDENTIFIED BY id-etsi-psd2-qcStatement }

id-etsi-psd2-qcStatement OBJECT IDENTIFIER :: =
{ itu-t(0) identified-organization(4) etsi(0) psd2(19495) qcstatement(2) }

PSD2QcType ::= SEQUENCE {
 rolesOfPSP RolesOfPSP,
 nCAName NCAName,
 nCAId NCAId }

NCAName ::= UTF8String (SIZE (1..256))

NCAId ::= UTF8String (SIZE (1..256))

RolesOfPSP ::= SEQUENCE OF RoleOfPSP

RoleOfPSP ::= SEQUENCE {
 roleOfPspOid RoleOfPspOid,
 roleOfPspName RoleOfPspName }

RoleOfPspOid ::= OBJECT IDENTIFIER

-- Object Identifier arc for roles of payment service providers
-- defined in the present document
etsi-psd2-roles OBJECT IDENTIFIER ::= { itu-t(0) identified-organization(4) etsi(0) psd2(19495) id-roles(1) }

-- Account Servicing Payment Service Provider (PSP_AS) role
id-psd2-role-psp-as OBJECT IDENTIFIER ::= { itu-t(0) identified-organization(4) etsi(0) psd2(19495) id-roles(1) 1 }

-- Payment Initiation Service Provider (PSP_PI) role
id-psd2-role-psp-pi OBJECT IDENTIFIER ::= { itu-t(0) identified-organization(4) etsi(0) psd2(19495) id-roles(1) 2 }

-- Account Information Service Provider (PSP_AI) role
id-psd2-role-psp-ai OBJECT IDENTIFIER ::= { itu-t(0) identified-organization(4) etsi(0) psd2(19495) id-roles(1) 3 }

-- Payment Service Provider issuing card-based payment instruments (PSP_IC) role
id-psd2-role-psp-ic OBJECT IDENTIFIER ::= { itu-t(0) identified-organization(4) etsi(0) psd2(19495) id-roles(1) 4 }

-- Payment Service Provider role name corresponding with OID (i.e. PSP_AS,
-- PSP_PI, PSP_AI, PSP_IC)

RoleOfPspName ::= UTF8String (SIZE(1..256))

-- Policy Identifiers
etsi-psd2-policy OBJECT IDENTIFIER ::= { itu-t(0) identified-organization(4) etsi(0) psd2(19495) policy-identifiers(3)}

-- QCP-w-psd2 certificate policy for PSD2 qualified website authentication certificates
qcp-web-psd2 OBJECT IDENTIFIER ::= { itu-t(0) identified-organization(4) etsi(0) psd2(19495) policy-identifiers(3) 1}
END 
```

I have tried to implement the spec above with pyasn1:

```py
from pyasn1.type import constraint
from pyasn1.type import univ
from pyasn1.type import namedtype
from pyasn1.type import char

from pyasn1.codec.der.decoder import decode

from pyasn1 import debug
debug.setLogger(debug.Debug('all'))

etsi_psd2_roles = univ.ObjectIdentifier('0.4.0.19495.1')
id_psd2_role_psp_as = univ.ObjectIdentifier('0.4.0.19495.1.1')
id_psd2_role_psp_pi = univ.ObjectIdentifier('0.4.0.19495.1.2')
id_psd2_role_psp_ai = univ.ObjectIdentifier('0.4.0.19495.1.3')
id_psd2_role_psp_ic = univ.ObjectIdentifier('0.4.0.19495.1.4')

class RoleOfPspOid(univ.ObjectIdentifier):
    subtypeSpec = univ.ObjectIdentifier.subtypeSpec + constraint.SingleValueConstraint(
        id_psd2_role_psp_as,
        id_psd2_role_psp_pi,
        id_psd2_role_psp_ai,
        id_psd2_role_psp_ai,
    )

class RoleOfPSP(univ.Sequence):
    componentType = namedtype.NamedTypes(
        namedtype.NamedType('roleOfPspOid', RoleOfPspOid()),
        namedtype.NamedType('roleOfPspName', char.UTF8String()),
    )

class RolesOfPSP(univ.SequenceOf):
    componentType = RoleOfPSP()

class PSD2QcType(univ.Sequence):
    componentType = namedtype.NamedTypes(
        namedtype.NamedType('rolesOfPSP', RolesOfPSP()),
        namedtype.NamedType('nCAName', char.UTF8String()),
        namedtype.NamedType('nCAId', char.UTF8String()),
    )

class QCStatement(univ.Sequence):
    """
    QCStatement ::= SEQUENCE {
        statementId   OBJECT IDENTIFIER,
        statementInfo ANY OPTIONAL
    }
    """
    componentType = namedtype.NamedTypes(
        namedtype.NamedType('statementId', univ.ObjectIdentifier()),
        namedtype.OptionalNamedType('statementInfo', RoleOfPSP()),
    )

class QCStatements(univ.SequenceOf):
    componentType = QCStatement()

data = b"0p0n\x06\x06\x04\x00\x81\x98'\x020d090\x11\x06\x07\x04\x00\x81\x98'\x01\x03\x0c\x06PSP_AI0\x11\x06\x07\x04\x00\x81\x98'\x01\x04\x0c\x06PSP_IC0\x11\x06\x07\x04\x00\x81\x98'\x01\x02\x0c\x06PSP_PI\x0c\x1fFinancial Supervisory Authority\x0c\x06FI-FSA"

print(decode(d, asn1Spec=QCStatements()))
```

This snippet raises the following exception:

```
2019-07-30 08:04:08,724 pyasn1: running pyasn1 0.4.5, debug flags all
2019-07-30 08:04:08,724 pyasn1: debug category 'all' enabled
2019-07-30 08:04:08,725 pyasn1: decoder called at scope  with state 0, working with up to 114 octets of substrate:
00000: 30 70 30 6E 06 06 04 00 81 98 27 02 30 64 30 39
00016: 30 11 06 07 04 00 81 98 27 01 03 0C 06 50 53 50
00032: 5F 41 49 30 11 06 07 04 00 81 98 27 01 04 0C 06
00048: 50 53 50 5F 49 43 30 11 06 07 04 00 81 98 27 01
00064: 02 0C 06 50 53 50 5F 50 49 0C 1F 46 69 6E 61 6E
00080: 63 69 61 6C 20 53 75 70 65 72 76 69 73 6F 72 79
00096: 20 41 75 74 68 6F 72 69 74 79 0C 06 46 49 2D 46
00112: 53 41
2019-07-30 08:04:08,725 pyasn1: tag decoded into <TagSet object at 0x1090c0240 tags 0:32:16>, decoding length
2019-07-30 08:04:08,725 pyasn1: value length decoded into 112, payload substrate is:
00000: 30 6E 06 06 04 00 81 98 27 02 30 64 30 39 30 11
00016: 06 07 04 00 81 98 27 01 03 0C 06 50 53 50 5F 41
00032: 49 30 11 06 07 04 00 81 98 27 01 04 0C 06 50 53
00048: 50 5F 49 43 30 11 06 07 04 00 81 98 27 01 02 0C
00064: 06 50 53 50 5F 50 49 0C 1F 46 69 6E 61 6E 63 69
00080: 61 6C 20 53 75 70 65 72 76 69 73 6F 72 79 20 41
00096: 75 74 68 6F 72 69 74 79 0C 06 46 49 2D 46 53 41
2019-07-30 08:04:08,725 pyasn1: candidate ASN.1 spec is QCStatements
2019-07-30 08:04:08,725 pyasn1: value decoder chosen for an ambiguous type by type ID 9
2019-07-30 08:04:08,725 pyasn1: codec SequenceOfDecoder chosen by ASN.1 spec, decoding value
2019-07-30 08:04:08,726 pyasn1: decoding type <QCStatement schema object at 0x1090c00f0 tagSet=<TagSet object at 0x1090759b0 tags 0:32:16> subtypeSpec=<ConstraintsIntersection object at 0x109075a90> componentType=<NamedTypes object at 0x1090b4e48 types <NamedType object at 0x1090b4c88 type statementId=<ObjectIdentifier schema object at 0x1090b48d0 tagSet <TagSet object at 0x1090750b8 tags 0:0:6>>>, <OptionalNamedType object at 0x1090b4e10 type statementInfo=<RoleOfPSP schema object at 0x1090b4cc0 tagSet=<TagSet object at 0x1090759b0 tags 0:32:16> subtypeSpec=<ConstraintsIntersection object at 0x109075a90> componentType=<NamedTypes object at 0x10908ca58 types <NamedType object at 0x10908c908 type roleOfPspOid=<RoleOfPspOid schema object at 0x10908c8d0 tagSet <TagSet object at 0x1090750b8 tags 0:0:6> subtypeSpec <ConstraintsIntersection object at 0x10908c860 consts <SingleValueConstraint object at 0x10908c898 consts <ObjectIdentifier value object at 0x1077de5c0 tagSet <TagSet object at 0x1090750b8 tags 0:0:6> payload [0.4.0.19495.1.1]>, <ObjectIdentifier value object at 0x1077de2e8 tagSet <TagSet object at 0x1090750b8 tags 0:0:6> payload [0.4.0.19495.1.2]>, <ObjectIdentifier value object at 0x1077f5828 tagSet <TagSet object at 0x1090750b8 tags 0:0:6> payload [0.4.0.19495.1.3]>, <ObjectIdentifier value object at 0x1077f5828 tagSet <TagSet object at 0x1090750b8 tags 0:0:6> payload [0.4.0.19495.1.3]>>>>>, <NamedType object at 0x10908ca20 type roleOfPspName=<UTF8String schema object at 0x10908c9e8 tagSet <TagSet object at 0x109082b38 tags 0:0:12> encoding utf-8>>> sizeSpec=<ConstraintsIntersection object at 0x109075ac8>>>> sizeSpec=<ConstraintsIntersection object at 0x109075ac8>> chosen by given `asn1Spec`
2019-07-30 08:04:08,726 pyasn1: decoder called at scope QCStatements with state 0, working with up to 112 octets of substrate:
00000: 30 6E 06 06 04 00 81 98 27 02 30 64 30 39 30 11
00016: 06 07 04 00 81 98 27 01 03 0C 06 50 53 50 5F 41
00032: 49 30 11 06 07 04 00 81 98 27 01 04 0C 06 50 53
00048: 50 5F 49 43 30 11 06 07 04 00 81 98 27 01 02 0C
00064: 06 50 53 50 5F 50 49 0C 1F 46 69 6E 61 6E 63 69
00080: 61 6C 20 53 75 70 65 72 76 69 73 6F 72 79 20 41
00096: 75 74 68 6F 72 69 74 79 0C 06 46 49 2D 46 53 41
2019-07-30 08:04:08,726 pyasn1: tag decoded into <TagSet object at 0x1090c0240 tags 0:32:16>, decoding length
2019-07-30 08:04:08,726 pyasn1: value length decoded into 110, payload substrate is:
00000: 06 06 04 00 81 98 27 02 30 64 30 39 30 11 06 07
00016: 04 00 81 98 27 01 03 0C 06 50 53 50 5F 41 49 30
00032: 11 06 07 04 00 81 98 27 01 04 0C 06 50 53 50 5F
00048: 49 43 30 11 06 07 04 00 81 98 27 01 02 0C 06 50
00064: 53 50 5F 50 49 0C 1F 46 69 6E 61 6E 63 69 61 6C
00080: 20 53 75 70 65 72 76 69 73 6F 72 79 20 41 75 74
00096: 68 6F 72 69 74 79 0C 06 46 49 2D 46 53 41
2019-07-30 08:04:08,726 pyasn1: candidate ASN.1 spec is QCStatement
2019-07-30 08:04:08,726 pyasn1: value decoder chosen for an ambiguous type by type ID 11
2019-07-30 08:04:08,726 pyasn1: codec SequenceDecoder chosen by ASN.1 spec, decoding value
2019-07-30 08:04:08,726 pyasn1: decoding non-deterministic  type <QCStatement schema object at 0x1090c00f0 tagSet=<TagSet object at 0x1090759b0 tags 0:32:16> subtypeSpec=<ConstraintsIntersection object at 0x109075a90> componentType=<NamedTypes object at 0x1090b4e48 types <NamedType object at 0x1090b4c88 type statementId=<ObjectIdentifier schema object at 0x1090b48d0 tagSet <TagSet object at 0x1090750b8 tags 0:0:6>>>, <OptionalNamedType object at 0x1090b4e10 type statementInfo=<RoleOfPSP schema object at 0x1090b4cc0 tagSet=<TagSet object at 0x1090759b0 tags 0:32:16> subtypeSpec=<ConstraintsIntersection object at 0x109075a90> componentType=<NamedTypes object at 0x10908ca58 types <NamedType object at 0x10908c908 type roleOfPspOid=<RoleOfPspOid schema object at 0x10908c8d0 tagSet <TagSet object at 0x1090750b8 tags 0:0:6> subtypeSpec <ConstraintsIntersection object at 0x10908c860 consts <SingleValueConstraint object at 0x10908c898 consts <ObjectIdentifier value object at 0x1077de5c0 tagSet <TagSet object at 0x1090750b8 tags 0:0:6> payload [0.4.0.19495.1.1]>, <ObjectIdentifier value object at 0x1077de2e8 tagSet <TagSet object at 0x1090750b8 tags 0:0:6> payload [0.4.0.19495.1.2]>, <ObjectIdentifier value object at 0x1077f5828 tagSet <TagSet object at 0x1090750b8 tags 0:0:6> payload [0.4.0.19495.1.3]>, <ObjectIdentifier value object at 0x1077f5828 tagSet <TagSet object at 0x1090750b8 tags 0:0:6> payload [0.4.0.19495.1.3]>>>>>, <NamedType object at 0x10908ca20 type roleOfPspName=<UTF8String schema object at 0x10908c9e8 tagSet <TagSet object at 0x109082b38 tags 0:0:12> encoding utf-8>>> sizeSpec=<ConstraintsIntersection object at 0x109075ac8>>>> sizeSpec=<ConstraintsIntersection object at 0x109075ac8>> chosen by type ID
2019-07-30 08:04:08,726 pyasn1: decoder called at scope QCStatements.QCStatement with state 0, working with up to 110 octets of substrate:
00000: 06 06 04 00 81 98 27 02 30 64 30 39 30 11 06 07
00016: 04 00 81 98 27 01 03 0C 06 50 53 50 5F 41 49 30
00032: 11 06 07 04 00 81 98 27 01 04 0C 06 50 53 50 5F
00048: 49 43 30 11 06 07 04 00 81 98 27 01 02 0C 06 50
00064: 53 50 5F 50 49 0C 1F 46 69 6E 61 6E 63 69 61 6C
00080: 20 53 75 70 65 72 76 69 73 6F 72 79 20 41 75 74
00096: 68 6F 72 69 74 79 0C 06 46 49 2D 46 53 41
2019-07-30 08:04:08,726 pyasn1: tag decoded into <TagSet object at 0x1090c04a8 tags 0:0:6>, decoding length
2019-07-30 08:04:08,726 pyasn1: value length decoded into 6, payload substrate is:
00000: 04 00 81 98 27 02
2019-07-30 08:04:08,727 pyasn1: candidate ASN.1 spec is ObjectIdentifier
2019-07-30 08:04:08,727 pyasn1: value decoder chosen for an ambiguous type by type ID 6
2019-07-30 08:04:08,727 pyasn1: codec ObjectIdentifierDecoder chosen by ASN.1 spec, decoding value
2019-07-30 08:04:08,727 pyasn1: codec ObjectIdentifierDecoder yields type ObjectIdentifier, value:
0.4.0.19495.2
...remaining substrate is:
00000: 30 64 30 39 30 11 06 07 04 00 81 98 27 01 03 0C
00016: 06 50 53 50 5F 41 49 30 11 06 07 04 00 81 98 27
00032: 01 04 0C 06 50 53 50 5F 49 43 30 11 06 07 04 00
00048: 81 98 27 01 02 0C 06 50 53 50 5F 50 49 0C 1F 46
00064: 69 6E 61 6E 63 69 61 6C 20 53 75 70 65 72 76 69
00080: 73 6F 72 79 20 41 75 74 68 6F 72 69 74 79 0C 06
00096: 46 49 2D 46 53 41
2019-07-30 08:04:08,727 pyasn1: decoder left scope QCStatements.QCStatement, call completed
2019-07-30 08:04:08,727 pyasn1: decoder called at scope QCStatements.QCStatement with state 0, working with up to 102 octets of substrate:
00000: 30 64 30 39 30 11 06 07 04 00 81 98 27 01 03 0C
00016: 06 50 53 50 5F 41 49 30 11 06 07 04 00 81 98 27
00032: 01 04 0C 06 50 53 50 5F 49 43 30 11 06 07 04 00
00048: 81 98 27 01 02 0C 06 50 53 50 5F 50 49 0C 1F 46
00064: 69 6E 61 6E 63 69 61 6C 20 53 75 70 65 72 76 69
00080: 73 6F 72 79 20 41 75 74 68 6F 72 69 74 79 0C 06
00096: 46 49 2D 46 53 41
2019-07-30 08:04:08,727 pyasn1: tag decoded into <TagSet object at 0x1090c0240 tags 0:32:16>, decoding length
2019-07-30 08:04:08,727 pyasn1: value length decoded into 100, payload substrate is:
00000: 30 39 30 11 06 07 04 00 81 98 27 01 03 0C 06 50
00016: 53 50 5F 41 49 30 11 06 07 04 00 81 98 27 01 04
00032: 0C 06 50 53 50 5F 49 43 30 11 06 07 04 00 81 98
00048: 27 01 02 0C 06 50 53 50 5F 50 49 0C 1F 46 69 6E
00064: 61 6E 63 69 61 6C 20 53 75 70 65 72 76 69 73 6F
00080: 72 79 20 41 75 74 68 6F 72 69 74 79 0C 06 46 49
00096: 2D 46 53 41
2019-07-30 08:04:08,727 pyasn1: candidate ASN.1 spec is a map of:
2019-07-30 08:04:08,727 pyasn1:   <TagSet object at 0x1090759b0 tags 0:32:16> -> RoleOfPSP
2019-07-30 08:04:08,727 pyasn1: new candidate ASN.1 spec is <TagSet object at 0x1090759b0 tags 0:32:16> -> RoleOfPSP {
 "roleOfPspOid" = <TagSet object at 0x1090750b8 tags 0:0:6> -> RoleOfPspOid
 "roleOfPspName" = <TagSet object at 0x109082b38 tags 0:0:12> -> UTF8String

}, chosen by <TagSet object at 0x1090c0240 tags 0:32:16>
2019-07-30 08:04:08,727 pyasn1: value decoder chosen for an ambiguous type by type ID 11
2019-07-30 08:04:08,727 pyasn1: codec SequenceDecoder chosen by ASN.1 spec, decoding value
2019-07-30 08:04:08,727 pyasn1: decoding deterministic  type <RoleOfPSP schema object at 0x1090b4cc0 tagSet=<TagSet object at 0x1090759b0 tags 0:32:16> subtypeSpec=<ConstraintsIntersection object at 0x109075a90> componentType=<NamedTypes object at 0x10908ca58 types <NamedType object at 0x10908c908 type roleOfPspOid=<RoleOfPspOid schema object at 0x10908c8d0 tagSet <TagSet object at 0x1090750b8 tags 0:0:6> subtypeSpec <ConstraintsIntersection object at 0x10908c860 consts <SingleValueConstraint object at 0x10908c898 consts <ObjectIdentifier value object at 0x1077de5c0 tagSet <TagSet object at 0x1090750b8 tags 0:0:6> payload [0.4.0.19495.1.1]>, <ObjectIdentifier value object at 0x1077de2e8 tagSet <TagSet object at 0x1090750b8 tags 0:0:6> payload [0.4.0.19495.1.2]>, <ObjectIdentifier value object at 0x1077f5828 tagSet <TagSet object at 0x1090750b8 tags 0:0:6> payload [0.4.0.19495.1.3]>, <ObjectIdentifier value object at 0x1077f5828 tagSet <TagSet object at 0x1090750b8 tags 0:0:6> payload [0.4.0.19495.1.3]>>>>>, <NamedType object at 0x10908ca20 type roleOfPspName=<UTF8String schema object at 0x10908c9e8 tagSet <TagSet object at 0x109082b38 tags 0:0:12> encoding utf-8>>> sizeSpec=<ConstraintsIntersection object at 0x109075ac8>> chosen by type ID
2019-07-30 08:04:08,728 pyasn1: decoder called at scope QCStatements.QCStatement.RoleOfPSP with state 0, working with up to 100 octets of substrate:
00000: 30 39 30 11 06 07 04 00 81 98 27 01 03 0C 06 50
00016: 53 50 5F 41 49 30 11 06 07 04 00 81 98 27 01 04
00032: 0C 06 50 53 50 5F 49 43 30 11 06 07 04 00 81 98
00048: 27 01 02 0C 06 50 53 50 5F 50 49 0C 1F 46 69 6E
00064: 61 6E 63 69 61 6C 20 53 75 70 65 72 76 69 73 6F
00080: 72 79 20 41 75 74 68 6F 72 69 74 79 0C 06 46 49
00096: 2D 46 53 41
2019-07-30 08:04:08,728 pyasn1: tag decoded into <TagSet object at 0x1090c0240 tags 0:32:16>, decoding length
2019-07-30 08:04:08,728 pyasn1: value length decoded into 57, payload substrate is:
00000: 30 11 06 07 04 00 81 98 27 01 03 0C 06 50 53 50
00016: 5F 41 49 30 11 06 07 04 00 81 98 27 01 04 0C 06
00032: 50 53 50 5F 49 43 30 11 06 07 04 00 81 98 27 01
00048: 02 0C 06 50 53 50 5F 50 49
2019-07-30 08:04:08,728 pyasn1: codec <none> chosen by ASN.1 spec, decoding as explicit tag
2019-07-30 08:04:08,728 pyasn1: codec <none> chosen, decoding as failure
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/testuser/projects/path/to/project/helpers/certificate.py", line 414, in <module>
    print(decode(d, asn1Spec=QCStatements()))
  File "/Users/testuser/projects/path/to/project/venv/lib/python3.7/site-packages/pyasn1/codec/ber/decoder.py", line 1498, in __call__
    **options
  File "/Users/testuser/projects/path/to/project/venv/lib/python3.7/site-packages/pyasn1/codec/ber/decoder.py", line 694, in valueDecoder
    component, head = decodeFun(head, componentType, **options)
  File "/Users/testuser/projects/path/to/project/venv/lib/python3.7/site-packages/pyasn1/codec/ber/decoder.py", line 1498, in __call__
    **options
  File "/Users/testuser/projects/path/to/project/venv/lib/python3.7/site-packages/pyasn1/codec/ber/decoder.py", line 608, in valueDecoder
    component, head = decodeFun(head, componentType, **options)
  File "/Users/testuser/projects/path/to/project/venv/lib/python3.7/site-packages/pyasn1/codec/ber/decoder.py", line 1498, in __call__
    **options
  File "/Users/testuser/projects/path/to/project/venv/lib/python3.7/site-packages/pyasn1/codec/ber/decoder.py", line 608, in valueDecoder
    component, head = decodeFun(head, componentType, **options)
  File "/Users/testuser/projects/path/to/project/venv/lib/python3.7/site-packages/pyasn1/codec/ber/decoder.py", line 1531, in __call__
    '%s not in asn1Spec: %r' % (tagSet, asn1Spec)
pyasn1.error.PyAsn1Error: <TagSet object at 0x1090c0240 tags 0:32:16> not in asn1Spec: <RoleOfPspOid schema object at 0x10908c8d0 tagSet <TagSet object at 0x1090750b8 tags 0:0:6> subtypeSpec <ConstraintsIntersection object at 0x10908c860 consts <SingleValueConstraint object at 0x10908c898 consts <ObjectIdentifier value object at 0x1077de5c0 tagSet <TagSet object at 0x1090750b8 tags 0:0:6> payload [0.4.0.19495.1.1]>, <ObjectIdentifier value object at 0x1077de2e8 tagSet <TagSet object at 0x1090750b8 tags 0:0:6> payload [0.4.0.19495.1.2]>, <ObjectIdentifier value object at 0x1077f5828 tagSet <TagSet object at 0x1090750b8 tags 0:0:6> payload [0.4.0.19495.1.3]>, <ObjectIdentifier value object at 0x1077f5828 tagSet <TagSet object at 0x1090750b8 tags 0:0:6> payload [0.4.0.19495.1.3]>>>>
```

I'd be happy to contribute examples and improve documentation once I'm able to fix this problem.

Thank you!

**Comment by holviberker** [comment]
You can ignore this issue. The problem was a user error. Sorry for the noise!
