### ISSUE TITLE
is it support python 3.6 ?

### ISSUE THREAD

**Issue by muhamedoufi** [etingof/pyasn1#221]
<pre>[2023-05-16 12:51:12,866: ERROR/ForkPoolWorker-1] poll error: Traceback (most recent call last):
;  File "/var/www/html/venv/lib/python3.6/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 46, in runDispatcher
    use_poll=True, map=self.__sockMap, count=1)
;  File "/usr/lib/python3.6/asyncore.py", line 207, in loop
    poll_fun(timeout, map)
;  File "/usr/lib/python3.6/asyncore.py", line 188, in poll2
    readwrite(obj, flags)
;  File "/usr/lib/python3.6/asyncore.py", line 123, in readwrite
    obj.handle_error()
;  File "/usr/lib/python3.6/asyncore.py", line 108, in readwrite
    obj.handle_read_event()
;  File "/usr/lib/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
;  File "/var/www/html/venv/lib/python3.6/site-packages/pysnmp/carrier/asyncore/dgram/base.py", line 170, in handle_read
    self._cbFun(self, transportAddress, incomingMessage)
;  File "/var/www/html/venv/lib/python3.6/site-packages/pysnmp/carrier/base.py", line 70, in _cbFun
    self, transportDomain, transportAddress, incomingMessage
;  File "/var/www/html/venv/lib/python3.6/site-packages/pysnmp/entity/engine.py", line 152, in __receiveMessageCbFun
    self, transportDomain, transportAddress, wholeMsg
;  File "/var/www/html/venv/lib/python3.6/site-packages/pysnmp/proto/rfc3412.py", line 291, in receiveMessage
    msgVersion = verdec.decodeMessageVersion(wholeMsg)
;  File "/var/www/html/venv/lib/python3.6/site-packages/pysnmp/proto/api/verdec.py", line 17, in decodeMessageVersion
    recursiveFlag=False, substrateFun=lambda a, b, c: (a, b[:c])
;  File "/var/www/html/venv/lib/python3.6/site-packages/pyasn1/codec/ber/decoder.py", line 2003, in __call__
    for asn1Object in streamingDecoder:
;  File "/var/www/html/venv/lib/python3.6/site-packages/pyasn1/codec/ber/decoder.py", line 1919, in __iter__
    self._substrate, self._asn1Spec, **self._options):
;  File "/var/www/html/venv/lib/python3.6/site-packages/pyasn1/codec/ber/decoder.py", line 1781, in __call__
    self, substrateFun, **options):
;  File "/var/www/html/venv/lib/python3.6/site-packages/pyasn1/codec/ber/decoder.py", line 654, in valueDecoder
    for chunk in substrateFun(asn1Object, substrate, length, options):
;TypeError: <lambda>() takes 3 positional arguments but 4 were given
caused by <class 'TypeError'>: <lambda>() takes 3 positional arguments but 4 were given
</pre>

**Comment by lextm** [comment]
Duplicate to https://github.com/pyasn1/pyasn1/issues/28
