### ISSUE TITLE
DER encoding error

### ISSUE THREAD

**Issue by Danfocus** [etingof/pyasn1#34]
Hi

Cannot encode with version 0.2.4

How to reproduce
```
>>> from pyasn1.codec.der import encoder
>>> from pyasn1.type import univ
>>> seq = univ.Sequence()
>>> seq.setComponentByPosition(0, univ.ObjectIdentifier("1.2.643.2.2.35.1"))
Sequence().setComponentByPosition(0, ObjectIdentifier('1.2.643.2.2.35.1'))
>>> encoder.encode(seq)
Traceback (most recent call last):
  File "<pyshell#489>", line 1, in <module>
    encoder.encode(seq)
  File "C:\Python36\lib\site-packages\pyasn1\codec\der\encoder.py", line 40, in __call__
    return encoder.Encoder.__call__(self, client, defMode, maxChunkSize)
  File "C:\Python36\lib\site-packages\pyasn1\codec\cer\encoder.py", line 149, in __call__
    return encoder.Encoder.__call__(self, client, defMode, maxChunkSize)
  File "C:\Python36\lib\site-packages\pyasn1\codec\ber\encoder.py", line 474, in __call__
    self, value, defMode, maxChunkSize
  File "C:\Python36\lib\site-packages\pyasn1\codec\ber\encoder.py", line 61, in encode
    encodeFun, value, defMode, maxChunkSize
  File "C:\Python36\lib\site-packages\pyasn1\codec\ber\encoder.py", line 347, in encodeValue
    if namedTypes[idx].isOptional and not value[idx].isValue:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by etingof** [comment]
Thank you for your report!

This is hopefully fixed in master. Please, reopen this issue in case of further nuisances. ;-)

BTW, you could shorten your code a bit by:

    seq[0] = univ.ObjectIdentifier("1.2.643.2.2.35.1")
