### ISSUE TITLE
no longer able to parse cert created with openssl

### ISSUE THREAD

**Issue by maximermilov** [etingof/pyasn1#61]
Test example works with pyasn1 0.1.8.
Stops working after upgrading to 0.3.2

```bash
→ openssl req -new -sha1 -x509 \
-days 3650 -extensions v3_ca \
-keyout ca.key \
-out ca_public_cert.pem \
-passout env:CAPASS
> > > > Generating a 2048 bit RSA private key
..............................................+++
............................................................................................................+++
writing new private key to 'ca.key'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:
State or Province Name (full name) [Some-State]:
Locality Name (eg, city) []:NYC
Organization Name (eg, company) [Internet Widgits Pty Ltd]:
Organizational Unit Name (eg, section) []:1
Common Name (e.g. server FQDN or YOUR name) []:ASD
Email Address []:
→ VE/bin/python test.py
→ VE/bin/pip install --upgrade pyasn1
Collecting pyasn1
  Downloading pyasn1-0.3.2-py2.py3-none-any.whl (63kB)
    100% |████████████████████████████████| 71kB 2.6MB/s 
Installing collected packages: pyasn1
  Found existing installation: pyasn1 0.1.8
    Uninstalling pyasn1-0.1.8:
      Successfully uninstalled pyasn1-0.1.8
Successfully installed pyasn1-0.3.2
→ VE/bin/python test.py
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    encaps_seq = der_decoder.decode(base64.b64decode(cert))
  File "/usr/local/google/home/maximermilov/tmp/2/VE/local/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 1008, in __call__
    stGetValueDecoder, self, substrateFun
  File "/usr/local/google/home/maximermilov/tmp/2/VE/local/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 382, in valueDecoder
    component, head = decodeFun(head, asn1Spec)
  File "/usr/local/google/home/maximermilov/tmp/2/VE/local/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 1008, in __call__
    stGetValueDecoder, self, substrateFun
  File "/usr/local/google/home/maximermilov/tmp/2/VE/local/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 382, in valueDecoder
    component, head = decodeFun(head, asn1Spec)
  File "/usr/local/google/home/maximermilov/tmp/2/VE/local/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 1008, in __call__
    stGetValueDecoder, self, substrateFun
  File "/usr/local/google/home/maximermilov/tmp/2/VE/local/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 382, in valueDecoder
    component, head = decodeFun(head, asn1Spec)
  File "/usr/local/google/home/maximermilov/tmp/2/VE/local/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 1008, in __call__
    stGetValueDecoder, self, substrateFun
  File "/usr/local/google/home/maximermilov/tmp/2/VE/local/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 382, in valueDecoder
    component, head = decodeFun(head, asn1Spec)
  File "/usr/local/google/home/maximermilov/tmp/2/VE/local/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 1015, in __call__
    '%s not in asn1Spec: %r' % (tagSet, asn1Spec)
pyasn1.error.PyAsn1Error: [0:32:16] not in asn1Spec: TagMap()
```

```python
import base64
from pyasn1.codec.der import decoder as der_decoder

cert = """MIIDsDCCApigAwIBAgIJAM/gviWR8zldMA0GCSqGSIb3DQEBBQUAMG0xCzAJBgNV
BAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMQwwCgYDVQQHDANOWUMxITAfBgNV
BAoMGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDEKMAgGA1UECwwBMTEMMAoGA1UE
AwwDQVNEMB4XDTE3MDgyMzE1MTA0OVoXDTI3MDgyMTE1MTA0OVowbTELMAkGA1UE
BhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxDDAKBgNVBAcMA05ZQzEhMB8GA1UE
CgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMQowCAYDVQQLDAExMQwwCgYDVQQD
DANBU0QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDArjzLvlWXAApZ
t0qXdNHT1Xn19ik8r33ioqDD2dFALUOkbSeMds10A7b6lGHb3e0nfYm84i+EbWvu
eDzzydkj+DvkFkx7xVdz/MPukA0LGd/uoEW25mI3ZLScECVsdX5ZPiV8DigPV/Hn
e/2sT7SVpLsUBxwyEsUBcnnDRKMx3FvmrCn/ZdfcvkarPIuHXPF+t+3gOvyWXwQ1
yrWo9eYczMNJ82Mm6GxVIp5UsWtMhHHMpLeSu/uudB4fkzdaBtEx20eMe9ZPBjYI
5q+i0VECuUUVAQoo9PI7tTkvOBRACvZ1WAgf3gFj/XsHLVXxr7zRweYLkj+MxSP4
8nJF0o71AgMBAAGjUzBRMB0GA1UdDgQWBBTkWG/uEpxWU2VI3O0dcawxxEoatTAf
BgNVHSMEGDAWgBTkWG/uEpxWU2VI3O0dcawxxEoatTAPBgNVHRMBAf8EBTADAQH/
MA0GCSqGSIb3DQEBBQUAA4IBAQAtMLyDdCvllyI6hM+XPWb4RmyivNtuaisVIZiP
tYa0/lD1K3w/jq29TPqYjS7p7ophuVL+AgtmomfrGnQHEEwch6ApBVc+rHUEXfcm
AY4n81mHWOTgHrjCYNmqQ7CAGed5YVRPI+g+2zdxnrNUO4u9GWD5g/UrN0NWur+k
V3PqKtZwzLqXCPYpArLeNkburFopFXCQOhMnR/E9BOTM1/50In09dC9uOSbg+p2x
4BD7Xg4Li9i+ypysTtoBOwc5xD3C2I7Z6Arlx++t4UIXPGuUYpIUJSWdJEqzMoXT
MvH09gS0d33qCxiO9BYqyEH7Bmp6Z4Zz7ZCxkWhZab+XNPVx"""

encaps_seq = der_decoder.decode(base64.b64decode(cert))
```

**Comment by etingof** [comment]
Thank you for reporting this! I am able to reproduce this, looking into the cause...

**Comment by etingof** [comment]
I believe this issue has been fixed in current master (specifically, commit https://github.com/etingof/pyasn1/commit/a46d54a535c06dce347028d7c5d7449e73bc9bab).

I'd appreciate if you could test it before I make a release (likely over weekend).

Thank you!

**Comment by maximermilov** [comment]
> I'd appreciate if you could test it before I make a release

Tested.
Thank you!
