### ISSUE TITLE
pyasn1.error.PyAsn1Error: Duplicate default ASN.1 type

### ISSUE THREAD

**Issue by tubaman** [etingof/pyasn1#68]
This following code used to work fine on 0.3.1 but breaks on 0.3.2 and 0.3.3:

```python
from pyasn1.type import univ, namedtype

class Foobar(univ.Sequence):
    pass

Foobar.componentType = namedtype.NamedTypes(
    namedtype.NamedType('baz', univ.Any()),
    namedtype.OptionalNamedType('blerg', univ.Any())
)
```

On 0.3.2 and 0.3.3, here's the traceback we get:
```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    namedtype.OptionalNamedType('blerg', univ.Any())
  File "/home/ryanow01/sandboxes/pyasn1_problem/.tox/pyasn1033/local/lib/python2.7/site-packages/pyasn1/type/namedtype.py", line 117, in __init__
    self.__nonUniqueTagMap = self.__computeTagMaps(unique=False)
  File "/home/ryanow01/sandboxes/pyasn1_problem/.tox/pyasn1033/local/lib/python2.7/site-packages/pyasn1/type/namedtype.py", line 441, in __computeTagMaps
    raise error.PyAsn1Error('Duplicate default ASN.1 type at %s' % (self,))
pyasn1.error.PyAsn1Error: Duplicate default ASN.1 type at NamedTypes(NamedType('baz', Any()), OptionalNamedType('blerg', Any()))
```

**Comment by etingof** [comment]
Thank you for reporting this bug!

Should be fixed by now in master (commit 976d8c90f5f0c8b22c43a13d8aa624c16fd5685a).
