### ISSUE TITLE
pyasn1-0.3.5: can only concatenate tuple (not "str") to tuple

### ISSUE THREAD

**Issue by asolino** [etingof/pyasn1#78]
Hey there:

First of all, thanks for this library. We use it extensively in our [impacket](https://github.com/CoreSecurity/impacket) repository.

While investigating [this](https://github.com/CoreSecurity/impacket/issues/325) issue, I came up with the following code not working:
```python
from pyasn1.codec.der import encoder
from pyasn1.type import univ, namedtype, tag

class KERB_PA_PAC_REQUEST(univ.Sequence):
    componentType = namedtype.NamedTypes(
    namedtype.NamedType('include-pac', univ.Boolean().subtype(explicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    )

pacRequest = KERB_PA_PAC_REQUEST()
pacRequest['include-pac'] = True
print pacRequest.prettyPrint()
encodedPacRequest = encoder.encode(pacRequest)

print repr(encodedPacRequest)
```
Under `pyasn1-0.3.5` I get the following traceback error:
```
Traceback (most recent call last):
  File "tt.py", line 12, in <module>
    encodedPacRequest = encoder.encode(pacRequest)
  File "/Users/beto/src/pyasn1-0.3.5/pyasn1/codec/ber/encoder.py", line 505, in __call__
    substrate = concreteEncoder.encode(value, self, **options)
  File "/Users/beto/src/pyasn1-0.3.5/pyasn1/codec/ber/encoder.py", line 73, in encode
    value, encodeFun, **options
  File "/Users/beto/src/pyasn1-0.3.5/pyasn1/codec/cer/encoder.py", line 145, in encodeValue
    substrate = encodeFun(value[idx], **options) + substrate
  File "/Users/beto/src/pyasn1-0.3.5/pyasn1/codec/ber/encoder.py", line 505, in __call__
    substrate = concreteEncoder.encode(value, self, **options)
  File "/Users/beto/src/pyasn1-0.3.5/pyasn1/codec/ber/encoder.py", line 89, in encode
    substrate = ints2octs(header + substrate)
TypeError: can only concatenate tuple (not "str") to tuple
```
while it works just fine with previous version.

Can you point out what are we doing wrong?

thanks.

**Comment by etingof** [comment]
Thanks for rising this!

I see the same thing with your reproducer. Looks like a bug to me.

Hope to come up with a fix tonight.

**Comment by etingof** [comment]
Alright, [here is the fix](https://github.com/etingof/pyasn1/pull/79) for you to test.

Thanks! ;-)

**Comment by asolino** [comment]
Hey @etingof 

Thanks for your quick answer.. just tested that PR and things are working now. Thanks!

**Comment by etingof** [comment]
Merged. This is a quite nasty bug - I think we need a release.
