### ISSUE TITLE
Uninstalling pyasn1==0.2.2 throws an apparently spurious exception

### ISSUE THREAD

**Issue by zancas** [etingof/pyasn1#80]
Hi there!

I ran `pip install -U .` in a clone of the repo checked out at tag `0.2.2` and, though the upgrade appeared to cause the correct transformation, the process raised an OSError.

I believe the cause is a bug in the uninstall logic

Replication:

0.  check that `pyasn1==0.2.2` is installed:

```
root@REDACTED:/home/jenkins# pip freeze | grep pyasn1
pyasn1==0.2.2
```

1.   check that `/usr/local/lib/python2.7/dist-packages/pyasn1-0.2.2-py2.7.egg` exists (and that other versions do not):

```
root@REDACTED:/home/jenkins# ls -la /usr/local/lib/python2.7/dist-packages/pyasn1*
-rw-r--r-- 1 root staff 119738 Sep 20 17:18 /usr/local/lib/python2.7/dist-packages/pyasn1-0.2.2-py2.7.egg
```

2.  uninstall `pyasn1`:

```
root@REDACTED:/home/jenkins# pip uninstall pyasn1
Uninstalling pyasn1-0.2.2:
  /usr/local/lib/python2.7/dist-packages/pyasn1-0.2.2-py2.7.egg
Proceed (y/n)? y
  Successfully uninstalled pyasn1-0.2.2
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    load_entry_point('pip==9.0.1', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/pyasn1-0.2.2-py2.7.egg'
```

3.  check the state of '/usr/local/lib/python2.7/dist-packages/pyasn1*`:

```
root@REDACTED:/home/jenkins# ls -la /usr/local/lib/python2.7/dist-packages/pyasn1*
ls: cannot access '/usr/local/lib/python2.7/dist-packages/pyasn1*': No such file or directory
```

My belief is that the `uninstall` command is correctly removing the referenced `.egg` and then incorrectly asserting that it expects the `.egg` to exist.    Since the uninstall logic is a component of the `pip install --upgrade` process, this causes my upgrade-dependent infrastructure to fail.

Thanks for your software!

**Comment by zancas** [comment]
Hmmm

This bug seems to only occur when I _initially_ install with:

`python setup.py install`

So `pip uninstall pyasn1` does work when install was also managed with `pip`.

**Comment by zancas** [comment]
It seems that `pip uninstall` specifically warns that this case is not supported:

https://pip.pypa.io/en/stable/reference/pip_uninstall/
